apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-draft
  labels:
    app: project-draft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-draft
  template:
    metadata:
      labels:
        app: project-draft
    spec:
      containers:
        - name: project-draft
          image: project-draft:release
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: APP_APPLICATION__HOST
              value: 0.0.0.0

